services:
  postgres:
    image: postgres:16
    container_name: user-management-app
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"
      POSTGRES_DB: ${DB_POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Mounts data to a named volume
    ports:
      - ${DB_POSTGRES_PORT}:5432 # Maps host port 5432 to container port 

volumes:
  postgres_data:
    driver: local
